#region General

- type: loadout
  id: SecurityVisor
  equipment:
    eyes: ClothingEyesVisorSecurity



#region Brigmedic

# Eyes

- type: loadout
  id: BrigmedicVisor
  equipment:
    eyes: ClothingEyesVisorBrigmedic

# Sidearm

- type: loadout
  id: SecurityRevolverOathbreaker
  dummyEntity: WeaponRevolverOathbreaker
  effects:
    - !type:JobRequirementLoadoutEffect
      requirement:
        !type:RoleTimeRequirement
        role: JobBrigmedic
        time: 36000 # Needs to be earned
  storage:
    back:
    - WeaponRevolverOathbreaker
    - SpeedLoaderShotgunBeanbag
    - SpeedLoaderShotgunBeanbag
    - SpeedLoaderMagnumBasic

- type: loadout
  id: SecurityRevolverOathbreakercustom
  dummyEntity: WeaponRevolverOathbreakercustom
  effects:
    - !type:JobRequirementLoadoutEffect
      requirement:
        !type:RoleTimeRequirement
        role: JobBrigmedic
        time: 360000 # Trust me, you don't wanna mess with a brig that knows how to transmute your blood into napalm+phlog mix
  storage:
    back:
    - WeaponRevolverOathbreakercustom
    - SpeedLoaderShotgunBeanbag
    - SpeedLoaderShotgunBeanbag
    - SpeedLoaderMagnumBasic
#region Cadet

# Uniform

- type: loadout
  id: CadetSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitSecCadet

- type: loadout
  id: CadetSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtSecCadet

#region Corpsman

# PDA

- type: loadout
  id: CorpsmanPDA
  equipment:
    id: CorpsmanPDA

- type: loadout
  id: VeteranCorpsmanPDA
  effects:
    - !type:JobRequirementLoadoutEffect
      requirement:
        !type:RoleTimeRequirement
        role: JobCorpsman
        time: 216000
  equipment:
    id: VeteranCorpsmanPDA

# Head

- type: loadout
  id: CorpsmanBeret
  equipment:
    head: ClothingHeadHatBeretCorpsman

# Jumpsuit

- type: loadout
  id: JumpsuitCorpsman
  equipment:
    jumpsuit: ClothingUniformJumpsuitCorpsman

- type: loadout
  id: JumpskirtCorpsman
  equipment:
    jumpsuit: ClothingUniformJumpskirtCorpsman

# Back

- type: loadout
  id: CorpsmanBackpack
  equipment:
    back: ClothingBackpackCorpsman

- type: loadout
  id: CorpsmanSatchel
  equipment:
    back: ClothingBackpackSatchelCorpsman

- type: loadout
  id: CorpsmanDuffel
  equipment:
    back: ClothingBackpackDuffelCorpsman

# Belt

- type: loadout
  id: CorpsmanBelt
  equipment:
    belt: ClothingBeltCorpsmanFilled

# Gloves

- type: loadout
  id: CorpsmanNitrile
  equipment:
    gloves: ClothingHandsGlovesNitrile

- type: loadout
  id: BlackNitrile
  equipment:
    gloves: ClothingHandsGlovesBlackNitrile


# Outerclothing

- type: loadout
  id: CorpsmanCoat
  equipment:
    outerClothing: ClothingOuterCoatCorpsmanFH

- type: loadout
  id: CorpsmanGlasses
  equipment:
    eyes: ClothingEyesGlassesCorpsman

- type: loadout
  id: CorpsmanHud
  equipment:
    eyes: ClothingEyesHudCorpsman

- type: loadout
  id: CorpsmanVisor
  equipment:
    eyes: ClothingEyesVisorCorpsman

# Sidearm

- type: loadout
  id: SecurityPistolPathology
  dummyEntity: WeaponPistolPathology
  effects:
    - !type:JobRequirementLoadoutEffect
      requirement:
        !type:RoleTimeRequirement
        role: JobCorpsman
        time: 36000 # Needs to be earned
  storage:
    back:
    - WeaponPistolPathology
    - MagazinePistolRubber
    - MagazinePistolSP
    - MagazinePistolSP

#region Detective

# Sidearm

- type: loadout
  id: SecurityRevolverInspector
  dummyEntity: WeaponRevolverInspector
  effects:
    - !type:JobRequirementLoadoutEffect
      requirement:
        !type:RoleTimeRequirement
        role: JobDetective
        time: 36000 # Needs to be earned
  storage:
    back:
    - WeaponRevolverInspector
    - SpeedLoaderMagnumSP
    - SpeedLoaderMagnumSP
    - SpeedLoaderMagnumRubber

- type: loadout
  id: SecurityRevolverInspectorcustom
  dummyEntity: WeaponRevolverInspectorcustom
  effects:
    - !type:JobRequirementLoadoutEffect
      requirement:
        !type:RoleTimeRequirement
        role: JobDetective
        time: 360000 # Gonna be the most competent detective you've seen or some guy who afked for 50 rounds
  storage:
    back:
    - WeaponRevolverInspectorcustom
    - SpeedLoaderMagnumSP
    - SpeedLoaderMagnumSP
    - SpeedLoaderMagnumRubber

- type: loadout
  id: DetectiveHorrificNecktie
  equipment:
    neck: ClothingNeckHorrific
  effects:
    - !type:GroupLoadoutEffect
      proto: MasterDet

- type: loadout
  id: SecurityRevolverInstigatorDet # Detective gets it as his starting firearm instead of the MK.
  dummyEntity: WeaponRevolverInstigator
  storage:
    back:
    - WeaponRevolverInstigator
    - SpeedLoaderRevolver38SP
    - SpeedLoaderRevolver38SP
    - SpeedLoaderRevolver38Rubber
#region Sec Officer

# Sidearm

- type: loadout
  id: SecurityRevolverInstigator
  dummyEntity: WeaponRevolverInstigator
  effects:
    - !type:JobRequirementLoadoutEffect
      requirement:
        !type:RoleTimeRequirement
        role: JobSecurityOfficer
        time: 36000 # Needs to be earned
  storage:
    back:
    - WeaponRevolverInstigator
    - SpeedLoaderRevolver38SP
    - SpeedLoaderRevolver38SP
    - SpeedLoaderRevolver38Rubber

- type: loadout
  id: SecurityRevolverInstigatorcustom
  dummyEntity: WeaponRevolverInstigatorcustom
  effects:
    - !type:JobRequirementLoadoutEffect
      requirement:
        !type:RoleTimeRequirement
        role: JobSecurityOfficer
        time: 360000 # Will still struggle with friendly fire.
  storage:
    back:
    - WeaponRevolverInspectorcustom
    - SpeedLoaderRevolver38SP
    - SpeedLoaderRevolver38SP
    - SpeedLoaderRevolver38Rubber

- type: loadout
  id: SecurityPistolMk58
  dummyEntity: WeaponPistolMk58
  effects:
    - !type:JobRequirementLoadoutEffect
      requirement:
        !type:RoleTimeRequirement
        role: JobSecurityOfficer
        time: 360000
  storage:
    back:
    - WeaponPistolMk58
    - MagazinePistolSP
    - MagazinePistolRubber
    - MagazinePistolRubber
    
#region Warden

# Sidearm

- type: loadout
  id: SecurityPistolDueProcess
  dummyEntity: WeaponPistolDP
  effects:
    - !type:JobRequirementLoadoutEffect
      requirement:
        !type:RoleTimeRequirement
        role: JobWarden
        time: 36000 # Needs to be earned
  storage:
    back:
    - WeaponPistolDP
    - MagazinePistol38Rubber
    - MagazinePistol38SP
    - MagazinePistol38SP